name: Test
on: [push, pull_request]
concurrency:
  group: py-test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.10']
        galaxy-branch: ['release_22.01', 'dev']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Precreate virtualenv
        run: python -m venv tests/galaxy_venv
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e test
        env:
          GRAVITY_TEST_GALAXY_BRANCH: ${{ matrix.galaxy-branch }}
          XDG_RUNTIME_DIR: /run/user/$UID
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
